1.
a)
CREATE TABLE StudentInfo (STU_ID INT PRIMARY KEY,
STU_NAME VARCHAR(100),
DOB DATE,
PHONE_NO VARCHAR(20),
EMAIL_ID VARCHAR(100),
ADDRESS VARCHAR(255));

b) 
CREATE TABLE CoursesInfo (COURSE_ID INT PRIMARY KEY,
COURSE_NAME VARCHAR(100),
COURSE_INSTRUCTOR_NAME VARCHAR(100));

c) 
CREATE TABLE EnrollmentInfo (ENROLLMENT_ID INT PRIMARY KEY,
STU_ID INT,
COURSE_ID INT,
ENROLL_STATUS VARCHAR(20),
FOREIGN KEY (STU_ID) REFERENCES StudentInfo(STU_ID),
FOREIGN KEY (COURSE_ID) REFERENCES CoursesInfo(COURSE_ID));

2.
INSERT INTO StudentInfo (STU_ID, STU_NAME, DOB, PHONE_NO, EMAIL_ID, ADDRESS)
VALUES (1, 'Will Smith', '2000-01-01', '1234567890', 'will.smith@email.com', '543 Ricky St'),
(2, 'JK Rowling', '2001-02-02', '9876543210', 'jk.rowling@email.com', '189 Rocky St');
INSERT INTO CoursesInfo (COURSE_ID, COURSE_NAME, COURSE_INSTRUCTOR_NAME)
VALUES (101, 'Mathematics', 'James'),
(102, 'Computer Science', 'Josesph');
INSERT INTO EnrollmentInfo (ENROLLMENT_ID, STU_ID, COURSE_ID, ENROLL_STATUS)
VALUES (1, 1, 101, 'Enrolled'),
(2, 1, 102, 'Enrolled'),
(3, 2, 101, 'Enrolled');

3)
a)
SELECT DISTINCT(s.STU_NAME), s.PHONE_NO, s.EMAIL_ID, e.ENROLL_STATUS
FROM StudentInfo s
JOIN EnrollmentInfo e ON s.STU_ID = e.STU_ID;
 
b)
SELECT c.COURSE_NAME
FROM CoursesInfo c
JOIN EnrollmentInfo e ON c.COURSE_ID = e.COURSE_ID
WHERE e.STU_ID = 1;

c)
SELECT COURSE_NAME, COURSE_INSTRUCTOR_NAME FROM CoursesInfo;
 
d)
SELECT * FROM CoursesInfo
WHERE COURSE_ID = 101;

e)
SELECT * FROM CoursesInfo
WHERE COURSE_ID IN (101, 102);
 
4.
a)
SELECT c.COURSE_NAME, COUNT(e.STU_ID) AS NUM_ENROLLED FROM CoursesInfo c
LEFT JOIN EnrollmentInfo e ON c.COURSE_ID = e.COURSE_ID
GROUP BY c.COURSE_NAME;

b)
SELECT s.STU_NAME FROM StudentInfo s
JOIN EnrollmentInfo e ON s.STU_ID = e.STU_ID
WHERE e.COURSE_ID = 101;
 
c)
SELECT c.COURSE_INSTRUCTOR_NAME, COUNT(e.STU_ID) AS NUM_ENROLLED FROM CoursesInfo c
JOIN EnrollmentInfo e ON c.COURSE_ID = e.COURSE_ID
GROUP BY c.COURSE_INSTRUCTOR_NAME;

d)
SELECT s.STU_NAME FROM StudentInfo s
JOIN EnrollmentInfo e ON s.STU_ID = e.STU_ID
GROUP BY s.STU_ID HAVING COUNT(e.COURSE_ID) > 1;
 
e)
SELECT c.COURSE_NAME, COUNT(e.STU_ID) AS NUM_ENROLLED FROM CoursesInfo c
JOIN EnrollmentInfo e ON c.COURSE_ID = e.COURSE_ID
GROUP BY c.COURSE_NAME ORDER BY NUM_ENROLLED DESC;